# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S_RcAkA2phDKllUC2KrG2ttGEfiqvWD3
"""

# Dictionary mapping allergy types to foods that may cause those allergies
allergies = {
    "gluten": ("bread", "brownie"),
    "crustacean": ("crab",),
    "fish": ("Tilapia",)
}

# Menu is a list of tuples, each containing a dish name and its price
Menu = [
    ("bread", 1),
    ("brownie", 3),
    ("crab", 6),
    ("Tilapia", 1),
]

# Prompt the user to input the allergies they have
allergy = str(input('What are you allergic to? :')).strip().lower()

# Print the updated menu after eliminating allergic dishes
for plate_name, price in eliminate_allergies(allergies, Menu, allergy):
    print(f"{plate_name} - {price:.2f}€")

# Prompt the user to input the allergies they have
allergy = str(input('What are you allergic to? :')).strip().lower()

# Function to eliminate dishes containing allergens from the menu
def eliminate_allergies(allergies, Menu, allergy):
    # Split the user's input into a list of allergy terms
    allergy_list = allergy.split()

    # Loop through each allergy in the user's input
    for allergies_index in allergy_list:
        # Get the list of dishes associated with the current allergy
        plate_list = allergies[allergies_index]

        # Check if the list of dishes is not a single string
        if type(plate_list) is not str:
            # Iterate over each dish in the allergy list
            for plates in plate_list:
                # Iterate over the dishes in the menu
                for menu_plates in Menu:
                    # If the dish is in the menu, remove it
                    if plates in menu_plates:
                        Menu.remove(menu_plates)
        else:
            # Handle the case where the allergen maps to a single dish
            for menu_plates in Menu:
                # If the dish is in the menu, remove it
                if plate_list in menu_plates:
                    Menu.remove(menu_plates)

    # Return the updated menu
    return Menu
